import * as yup from 'yup';

export default yup.object().shape({
  dogid: yup.number().integer().required('Dog ID is required'),
  facilityid: yup.number().integer().required('Facility ID is required'),
  groupnum: yup.number().integer().required('Group number is required'),
  graddate: yup.string().required('Graduation date is required'),
  dogname: yup.string().required('Dog name is required'),
  age: yup.number().integer().required('Age is required'),
  shelter: yup.string().required('Shelter is required'),
  breed: yup.string().required('Breed is required'),
  chiptype: yup.string().required('Chip type is required'),
  chipnum: yup.number().integer().required('Chip number is required'),
  gender: yup.string().required('Gender is required'),
  altname: yup.string().required('Alternate name is required'),
  adoptername: yup.string().required('Adopter name is required'),
  adopterphone: yup.number().integer().required('Adopter phone is required'),
  addrline: yup.string().required('Address line is required'),
  adoptcity: yup.string().required('Adopter city is required'),
  adoptstate: yup.string().required('Adopter state is required'),
  zip: yup.number().integer().required('Zip is required'),
  adoptemail: yup.string().required('Adopter email is required'),
  fees: yup.number().integer().required('Fees is required'),
  revenue: yup.number().required('Revenue is required'),
  service: yup.boolean().required('Service is required'),
  therapy: yup.boolean().required('Therapy is required'),
  staffAdoption: yup.boolean().required('Staff Adoption is required'),
  specialNeeds: yup.boolean().required('Special needs is required'),
  deceased: yup.boolean().required('Deceased is required'),
  facilityUnit: yup.string().required('Facility unit is required'),
});
